spring.application.name=mcp-web-crawler
spring.main.web-application-type=none

spring.ai.mcp.server.name=web-crawler-mcp-server-stdio
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.stdio=true
# Disable banner and console logging so STDIO transport is clean
spring.main.banner-mode=off
logging.level.root=OFF

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:crawlerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
